#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

# Generate the base block mesh
runApplication blockMesh

# Run the solver
runApplication $(getApplication)

#------------------------------------------------------------------------------