#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Compile OpenFOAM libraries
wmake $targetType meshTools/topoSet/cellSources/spheresToCell

wmake $targetType phaseSystemModels/multiphaseInter/phasesSystem

wmake $targetType thermophysicalModels/radiation/radiationModels/laserDTRM

wmake $targetType laserHeatSource

wmake $targetType fvOptions/sources/derived/gaussianHeatSource

wmake $targetType geometricVoF